/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:ffeec003-f47f-45d5-ac8e-5acad69ca110",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ngyBcGcsE",
    "aws_user_pools_web_client_id": "3md0ro42b3rvf1bhp1aau62n9q",
    "oauth": {},
    "aws_user_files_s3_bucket": "pitch122630-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
